services:
  db:
    image: mysql:8
    volumes:
      #- db_data:/var/lib/mysql #parametro original
      - ./db:/var/lib/mysql #almacenando los datos fuera del contenedor
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: Passw0rd

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
#Inicio Nueva Linea proyectos
      - ${PWD}/temas/ElInformador:/var/www/html/wp-content/themes/ElInformador #Tema ya creado solo lo cargo para verificar funcionamiento
      - ${PWD}/temas/DevWP:/var/www/html/wp-content/themes/DevWP #Tema para desarrollo este es en el que voy a trabajar
      #- ${PWD}/temas/SUITE_ADOBE_ori.zip:/var/www/html/wp-content/themes/suite.zip #Test
#Fin Nueva Linea proyectos
#Inicio para almacenar plugins fuera del contenedor
      - ${PWD}/plugins/:/var/www/html/wp-content/plugins/
#Fin
#Inicio para almacenar archivos multimedia fuera del contenedor y luego mapearlo
      - ${PWD}/multimedia:/var/www/html/wp-content/uploads
#Fin
    ports:
      - "8000:80"
    restart: always

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: Passw0rd
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}
  wordpress_data: {}
